#!/usr/bin/env python3
"""
train_signs.py - Train YOLOv8n on the EsiBot GTSRB dataset
==========================================================
Runs prepare_gtsrb.py if needed, then trains YOLOv8n.

Usage:
  python3 train_signs.py \
      --dataset ~/robot_ws/src/esibot_vision/dataset/dataset.yaml \
      --output  ~/robot_ws/src/esibot_vision/models \
      --epochs  50 \
      --batch   16 \
      --imgsz   128

Model saved to <output>/signs_best.pt
"""

import argparse
import os
import shutil


def main():
    parser = argparse.ArgumentParser(description="Train YOLOv8n on EsiBot GTSRB")
    parser.add_argument(
        "--dataset",
        required=True,
        help="Path to dataset.yaml (generated by prepare_gtsrb.py)",
    )
    parser.add_argument(
        "--output", required=True, help="Output folder for signs_best.pt"
    )
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument(
        "--imgsz",
        type=int,
        default=128,
        help="Image size (64|128|160|320). 128 recommended for ESP32-CAM",
    )
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument(
        "--device",
        type=str,
        default="",
        help="Torch device: '' (auto), 'cpu', '0' (GPU 0)",
    )
    args = parser.parse_args()

    dataset = os.path.expanduser(args.dataset)
    output = os.path.expanduser(args.output)

    if not os.path.isfile(dataset):
        raise FileNotFoundError(
            f"dataset.yaml not found: {dataset}\n" f"Run prepare_gtsrb.py first"
        )

    os.makedirs(output, exist_ok=True)

    # -- Import ultralytics -----------------------------------------------
    try:
        from ultralytics import YOLO
    except ImportError:
        raise ImportError("Install ultralytics: pip install ultralytics")

    print(f"[train_signs] Dataset  : {dataset}")
    print(f"[train_signs] Output   : {output}")
    print(f"[train_signs] Epochs   : {args.epochs}")
    print(f"[train_signs] Batch    : {args.batch}")
    print(f"[train_signs] Img size : {args.imgsz}")

    # -- Load pre-trained YOLOv8n -----------------------------------------
    model = YOLO("yolov8n.pt")

    # -- Training ----------------------------------------------------------
    train_args = dict(
        data=dataset,
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        workers=args.workers,
        project=os.path.join(output, "runs"),
        name="signs",
        exist_ok=True,
        val=True,
        plots=True,
        verbose=True,
    )
    if args.device:
        train_args["device"] = args.device

    results = model.train(**train_args)

    # -- Copy best.pt to models/signs_best.pt ------------------------------
    best_src = os.path.join(output, "runs", "signs", "weights", "best.pt")
    best_dst = os.path.join(output, "signs_best.pt")

    if os.path.isfile(best_src):
        shutil.copy2(best_src, best_dst)
        print(f"\n[train_signs] Model saved: {best_dst}")
    else:
        print(f"\n[train_signs] WARNING: best.pt not found at {best_src}")
        print(f"             Look in {output}/runs/signs/weights/")

    print("[train_signs] Training finished.")


if __name__ == "__main__":
    main()
